colors = ["orange","yellow","green","blue","purple"]
colors2= ["white","black"]
print(colors)
colors.append("red") #adds a new at the end of the list
print(colors)
colors.insert(0, "red")
print(colors)
colors.extend(colors2) 
print(colors)
deleted_color= colors.pop()
print(colors)
print(f"deleted color = {deleted_color}")
colors.reverse()
print(colors)
colors.sort()
print(colors)
list2= sorted(colors)
colors.remove("red")
print(colors)
print(list(enumerate(colors)))
print("gray" in colors)
strcolors= ", ".join(colors)
print(strcolors)
print(type(strcolors))
colors3= strcolors.split(", ")
print(colors3)